import { createFileRoute } from "@tanstack/react-router";
import { useQuery,useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Card,CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { useAuth } from "@/lib/auth";

export const Route=createFileRoute("/admin/tickets")({head:()=>({meta:[{title:"Support Tickets — Admin"},{name:"robots",content:"noindex"}]}),component:TicketsPage});
type CaseRow={id:string;case_number:string;order_number:string|null;shop_name:string|null;subject:string;issue_category:string|null;issue_type:string|null;affected_item_name:string|null;support_stage:string;status:string;resolution_type:string|null;created_at:string;updated_at:string;viewer_role:string};
type Message={id:string;sender_role:string;body:string;attachments:string[];created_at:string;visible_to_customer:boolean;visible_to_vendor:boolean};
function TicketsPage(){
 const qc=useQueryClient();const auth=useAuth();const [selected,setSelected]=useState<string|null>(null);const [drafts,setDrafts]=useState<Record<string,string>>({});
 const cases=useQuery({queryKey:["protected-support-cases",auth.user?.id],enabled:!!auth.user,queryFn:async()=>{const {data,error}=await(supabase as any).rpc("get_protected_support_cases");if(error)throw error;return(data??[]) as CaseRow[];},refetchInterval:12000});
 const messages=useQuery({queryKey:["protected-support-messages",auth.user?.id,selected],enabled:!!auth.user&&!!selected,queryFn:async()=>{const {data,error}=await(supabase as any).rpc("admin_get_protected_support_messages",{p_ticket_id:selected});if(error)throw error;return(data??[]) as Message[];},refetchInterval:8000});
 const openAttachment=async(path:string)=>{const {data,error}=await supabase.storage.from("support-evidence").createSignedUrl(path,600);if(error||!data?.signedUrl){toast.error("Could not open private attachment.");return;}window.open(data.signedUrl,"_blank","noopener,noreferrer");};
 const run=async(id:string,fn:string,args:Record<string,unknown>,success:string)=>{const {error}=await(supabase as any).rpc(fn,{p_ticket_id:id,...args});if(error){toast.error(error.message);return;}toast.success(success);await qc.invalidateQueries({queryKey:["protected-support-cases"]});await qc.invalidateQueries({queryKey:["protected-support-messages",auth.user?.id,id]});};
 const send=async(id:string)=>{const text=drafts[id]?.trim();if(!text)return;await run(id,"send_protected_support_message",{p_body:text},"Message sent through LocalShore.");setDrafts(v=>({...v,[id]:""}));};
 return <main className="space-y-4"><header><h1 className="text-2xl font-black tracking-tight sm:text-3xl">Support Console</h1><p className="text-sm text-muted-foreground">Customer Care can review, mediate, escalate, and close protected cases. Refund actions remain subject to existing authorization rules.</p></header>
 {cases.isLoading?<div className="h-24 animate-pulse rounded-xl bg-muted"/>:cases.error?<Card><CardContent className="py-12 text-center text-sm text-muted-foreground">Could not load cases. Confirm the protected support migration has been applied.</CardContent></Card>:!cases.data?.length?<Card><CardContent className="py-12 text-center text-sm text-muted-foreground">No support cases found.</CardContent></Card>:<div className="space-y-3">{cases.data.map(c=><Card key={c.id}><CardContent className="space-y-3 p-4"><div className="flex flex-wrap items-center gap-2"><div className="mr-auto"><p className="text-xs font-bold text-primary">{c.case_number}</p><h2 className="font-semibold">{c.subject}</h2></div><Badge variant="outline" className="capitalize">{c.support_stage.replaceAll("_"," ").toLowerCase()}</Badge></div>
 <p className="text-xs text-muted-foreground">{c.order_number?`Order ${c.order_number}`:"General support"}{c.shop_name?` · ${c.shop_name}`:""}{c.affected_item_name?` · ${c.affected_item_name}`:""}{c.issue_type?` · ${c.issue_type.replaceAll("_"," ")}`:""} · {c.viewer_role}</p>
 <div className="rounded-lg border bg-muted/20 p-3"><div className="flex items-center justify-between"><p className="text-xs font-bold">Mediated conversation</p><Button size="sm" variant="ghost" onClick={()=>setSelected(selected===c.id?null:c.id)}>{selected===c.id?"Hide":"View conversation"}</Button></div>{selected===c.id&&<><p className="mt-1 text-[11px] text-muted-foreground">Customer and shop messages are private to their sender and Customer Care until you choose to share them.</p><div className="mt-2 max-h-80 space-y-2 overflow-y-auto">{messages.isLoading?<p className="text-xs">Loading…</p>:messages.data?.map(m=><article key={m.id} className="rounded-md bg-background p-2"><p className="text-[10px] font-bold uppercase text-muted-foreground">{m.sender_role==="customer_care"?"LocalShore Customer Care":m.sender_role==="system"?"LocalShore System":m.sender_role.replaceAll("_"," ")}</p><p className="whitespace-pre-wrap text-sm">{m.body}</p>{m.attachments?.map(path=><button key={path} className="mt-1 block text-xs text-primary underline" onClick={()=>void openAttachment(path)}>View private attachment</button>)}<div className="mt-1 flex flex-wrap items-center gap-2"><time className="mr-auto text-[10px] text-muted-foreground">{new Date(m.created_at).toLocaleString()}</time>{m.sender_role==="customer"&&!m.visible_to_vendor&&<Button size="sm" variant="outline" onClick={()=>void run(c.id,"forward_protected_support_message",{p_message_id:m.id,p_target_role:"vendor"},"Customer message shared with the shop.")}>Share with shop</Button>}{["vendor","delivery_partner"].includes(m.sender_role)&&!m.visible_to_customer&&<Button size="sm" variant="outline" onClick={()=>void run(c.id,"forward_protected_support_message",{p_message_id:m.id,p_target_role:"customer"},"Shop message shared with the customer.")}>Share with customer</Button>}</div></article>)}</div><div className="mt-2 flex gap-2"><input value={drafts[c.id]??""} onChange={e=>setDrafts(v=>({...v,[c.id]:e.target.value}))} maxLength={2000} placeholder="Message as LocalShore Customer Care…" className="min-w-0 flex-1 rounded-md border bg-background px-3 py-2 text-sm"/><Button size="sm" onClick={()=>void send(c.id)}>Send to both parties</Button></div></>}</div>
 <div className="flex flex-wrap gap-2">{[["wait_vendor","Ask shop to respond"],["escalate","Escalate"],["reopen","Reopen"],["resolve","Resolve case"],["cancel","Close case"]].map(([action,label])=><Button key={action} size="sm" variant={action==="resolve"?"default":"outline"} onClick={()=>void run(c.id,"manage_protected_support_case",{p_action:action,p_note:"Updated by Customer Care."},`Case ${label.toLowerCase()}.`)}>{label}</Button>)}</div>
 </CardContent></Card>)}</div>}
 </main>;
}
